# Generated by Django 3.2.8 on 2021-10-17 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 17, 13, 16, 6, 466923, tzinfo=utc), verbose_name='End Date'),
        ),
    ]
