# Generated by Django 3.2.8 on 2021-10-17 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_task_task_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date'),
        ),
    ]
